export const STAT_DEFS: Record<string, string> = {
  gp: 'Games Played',
  min: 'Minutes Per Game',
  pts: 'Points Per Game',
  reb: 'Total Rebounds Per Game',
  ast: 'Assists Per Game',
  stl: 'Steals Per Game',
  blk: 'Blocks Per Game',
  dreb: 'Defensive Rebounds Per Game',
  oreb: 'Offensive Rebounds Per Game',
  fg_pct: 'Field Goal Percentage',
  fg3_pct: 'Three-Point Field Goal Percentage',
  ft_pct: 'Free Throw Percentage',
  plus_minus: 'Net points scored vs. allowed while this player was on the court, per game',
  ts_pct: 'True Shooting % — efficiency weighting 2P, 3P, and FT equally',
  usg_pct: 'Usage Rate — % of team plays used by this player while on court',
  off_rating: 'Offensive Rating — points scored per 100 possessions',
  def_rating: 'Defensive Rating — points allowed per 100 possessions (lower = better)',
  net_rating: 'Net Rating — offensive minus defensive rating',
  ast_pct: 'Assist % — % of teammate field goals assisted while on court',
  oreb_pct: 'Offensive Rebound % — % of available offensive rebounds grabbed',
  dreb_pct: 'Defensive Rebound % — % of available defensive rebounds grabbed',
  reb_pct: 'Total Rebound %',
  pie: 'Player Impact Estimate — overall contribution metric (league avg ≈ 0.100)',
  def_ws: 'Defensive Win Shares',
  opp_pts_paint: 'Opponent Points in the Paint Allowed',
  opp_pts_2nd_chance: 'Opponent 2nd-Chance Points Allowed',
  opp_pts_off_tov: 'Opponent Points off Turnovers Allowed',
  season: 'Season',
  wins: 'Wins (team season)',
  losses: 'Losses (team season)',
  w: 'Wins',
  l: 'Losses',
  w_pct: 'Win Percentage',
  GROUP_VALUE: 'Split Category',
  game_date: 'Game date',
  matchup: 'Opponent and home/away context',
  wl: 'Win or loss for the player’s team',
  tov: 'Turnovers',
  pf: 'Personal fouls',
  fgm: 'Field goals made',
  fga: 'Field goal attempts',
  fg3m: 'Three-pointers made',
  fg3a: 'Three-point attempts',
  ftm: 'Free throws made',
  fta: 'Free throw attempts',
  rank: 'Leaderboard position',
  display_name: 'Player name',
  position: 'Primary position',
  team: 'Team abbreviation (current or record season)',
  value: 'Statistic value for this record',
  action: 'Quick actions for this row',
  conference_rank: 'Conference standing (1 = best in conference)',
  games_back: 'Games behind the conference leader',
  home_record: 'Home wins and losses',
  road_record: 'Road wins and losses',
  streak: 'Current win/loss streak',
  last10: 'Record in the last 10 games',
}
